<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'block_id'                 => '',
	'range'                    => '5',
	'rating'                   => '4',
	'size'                     => 18,
	'sizeTablet'               => 18,
	'sizeMobile'               => 18,
	'align'                    => 'left',
	'layout'                   => 'inline',
	'layoutTablet'             => 'inline',
	'layoutMobile'             => 'inline',
	'gap'                      => 2,
	'gapTablet'                => '',
	'gapMobile'                => '',
	'unmarkedColor'            => '#ccd6df',
	'color'                    => '#f0ad4e',
	'fontFamily'               => 'Default',
	'fontWeight'               => '',
	'fontSizeType'             => 'px',
	'fontSize'                 => '',
	'fontSizeMobile'           => '',
	'fontSizeTablet'           => '',
	'lineHeightType'           => 'em',
	'lineHeight'               => '',
	'lineHeightMobile'         => '',
	'lineHeightTablet'         => '',
	'titleColor'               => '',
	'titleGap'                 => 10,
	'titleGapTablet'           => 10,
	'titleGapMobile'           => 10,
	'fontStyle'                => '',
	'fontTransform'            => '',
	'fontDecoration'           => '',
	// letter spacing.
	'letterSpacing'            => '',
	'letterSpacingTablet'      => '',
	'letterSpacingMobile'      => '',
	'letterSpacingType'        => 'px',
	'alignTablet'              => '',
	'alignMobile'              => '',
	// padding.
	'blockTopPadding'          => '',
	'blockRightPadding'        => '',
	'blockLeftPadding'         => '',
	'blockBottomPadding'       => '',
	'blockTopPaddingTablet'    => '',
	'blockRightPaddingTablet'  => '',
	'blockLeftPaddingTablet'   => '',
	'blockBottomPaddingTablet' => '',
	'blockTopPaddingMobile'    => '',
	'blockRightPaddingMobile'  => '',
	'blockLeftPaddingMobile'   => '',
	'blockBottomPaddingMobile' => '',
	'blockPaddingUnit'         => 'px',
	'blockPaddingUnitTablet'   => 'px',
	'blockPaddingUnitMobile'   => 'px',
	'blockPaddingLink'         => '',
	// margin.
	'blockTopMargin'           => '',
	'blockRightMargin'         => '',
	'blockLeftMargin'          => '',
	'blockBottomMargin'        => '',
	'blockTopMarginTablet'     => '',
	'blockRightMarginTablet'   => '',
	'blockLeftMarginTablet'    => '',
	'blockBottomMarginTablet'  => '',
	'blockTopMarginMobile'     => '',
	'blockRightMarginMobile'   => '',
	'blockLeftMarginMobile'    => '',
	'blockBottomMarginMobile'  => '',
	'blockMarginUnit'          => 'px',
	'blockMarginUnitTablet'    => 'px',
	'blockMarginUnitMobile'    => 'px',
	'blockMarginLink'          => '',
	'starPosition'             => 'after',
	'starPositionTablet'       => 'after',
	'starPositionMobile'       => 'after',
);
