<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'classMigrate'             => false,
	'childMigrate'             => false,
	'align'                    => 'left',
	'alignTablet'              => '',
	'alignMobile'              => '',
	'icon_count'               => '1',
	'icons'                    => array(
		array(
			'label'                   => __( 'Label #1', 'ultimate-addons-for-gutenberg' ),
			'image_icon'              => 'icon',
			'icon'                    => '',
			'image'                   => '',
			'icon_color'              => '',
			'icon_hover_color'        => '',
			'icon_bg_color'           => '',
			'icon_bg_hover_color'     => '',
			'icon_border_color'       => '',
			'icon_border_hover_color' => '',
			'label_color'             => '',
			'label_hover_color'       => '',
			'link'                    => '#',
			'target'                  => false,
		),
	),
	'gap'                      => '10',
	'gapTablet'                => '',
	'gapMobile'                => '',
	'gapType'                  => 'px',
	'inner_gap'                => '15',
	'innerGapTablet'           => '',
	'innerGapMobile'           => '',
	'innerGapType'             => 'px',
	'size'                     => '16',
	'sizeType'                 => 'px',
	'sizeMobile'               => '',
	'sizeTablet'               => '',
	'bgSize'                   => '0',
	'bgSizeType'               => 'px',
	'bgSizeTablet'             => '',
	'bgSizeMobile'             => '',
	'border'                   => '0',
	'borderTablet'             => '',
	'borderMobile'             => '',
	'borderType'               => 'px',
	'borderRadius'             => '0',
	'borderRadiusTablet'       => '',
	'borderRadiusMobile'       => '',
	'borderRadiusType'         => 'px',
	'fontSize'                 => '',
	'fontSizeType'             => 'px',
	'fontSizeMobile'           => '',
	'fontSizeTablet'           => '',
	'lineHeight'               => '',
	'lineHeightType'           => 'em',
	'lineHeightMobile'         => '',
	'lineHeightTablet'         => '',
	'fontFamily'               => '',
	'fontWeight'               => '',
	'loadGoogleFonts'          => false,
	'icon_layout'              => 'vertical',
	'iconLayoutTablet'         => '',
	'iconLayoutMobile'         => '',
	'fontStyle'                => '',
	'fontTransform'            => '',
	'fontDecoration'           => '',
	'hideLabel'                => false,
	'iconPosition'             => 'middle',
	'iconPositionTablet'       => '',
	'iconPositionMobile'       => '',
	'iconPlacement'            => 'before',
	'iconColor'                => '',
	'iconHoverColor'           => '',
	'iconBgColor'              => '',
	'iconBgHoverColor'         => '',
	'iconBorderColor'          => '',
	'iconBorderHoverColor'     => '',
	'labelColor'               => '',
	'labelHoverColor'          => '',
	'labelLetterSpacing'       => '',
	'labelLetterSpacingTablet' => '',
	'labelLetterSpacingMobile' => '',
	'labelLetterSpacingType'   => 'px',
	// margin.
	'blockTopMargin'           => '',
	'blockRightMargin'         => '',
	'blockLeftMargin'          => '',
	'blockBottomMargin'        => '',
	'blockTopMarginTablet'     => '',
	'blockRightMarginTablet'   => '',
	'blockLeftMarginTablet'    => '',
	'blockBottomMarginTablet'  => '',
	'blockTopMarginMobile'     => '',
	'blockRightMarginMobile'   => '',
	'blockLeftMarginMobile'    => '',
	'blockBottomMarginMobile'  => '',
	'blockMarginUnit'          => 'px',
	'blockMarginUnitTablet'    => 'px',
	'blockMarginUnitMobile'    => 'px',
	'blockMarginLink'          => '',
	'parentIcon'               => 'circle-arrow-right',
	// padding.
	'blockTopPadding'          => '',
	'blockRightPadding'        => '',
	'blockLeftPadding'         => '',
	'blockBottomPadding'       => '',
	'blockTopPaddingTablet'    => '',
	'blockRightPaddingTablet'  => '',
	'blockLeftPaddingTablet'   => '',
	'blockBottomPaddingTablet' => '',
	'blockTopPaddingMobile'    => '',
	'blockRightPaddingMobile'  => '',
	'blockLeftPaddingMobile'   => '',
	'blockBottomPaddingMobile' => '',
	'blockPaddingUnit'         => 'px',
	'blockPaddingUnitTablet'   => 'px',
	'blockPaddingUnitMobile'   => 'px',
	'blockPaddingLink'         => '',
);
