<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

return array(
	'block_id'                 => '',
	'c_id'                     => null,
	'cookies'                  => false,
	'close_cookie_days'        => 1,
	'textColor'                => '',
	'titleColor'               => '',
	'noticeColor'              => '#FFD54F',
	'contentBgColor'           => '',
	'fontSize'                 => '14',
	'icon'                     => 'rectangle-xmark',
	'iconSize'                 => 16,
	'iconSizeTab'              => '',
	'iconSizeMob'              => '',
	'iconSizeUnit'             => 'px',
	'noticeDismiss'            => '',
	'noticeDismissColor'       => '',
	'noticeAlignment'          => 'left',
	'titleFontFamily'          => 'Default',
	'titleFontWeight'          => '',
	'titleFontSizeType'        => 'px',
	'titleLineHeightType'      => '',
	'titleFontSize'            => '',
	'titleFontSizeTablet'      => '',
	'titleFontSizeMobile'      => '',
	'titleLineHeight'          => '',
	'titleLineHeightTablet'    => '',
	'titleLineHeightMobile'    => '',
	'descFontFamily'           => 'Default',
	'descFontWeight'           => '',
	'descFontSize'             => '',
	'descFontSizeType'         => 'px',
	'descFontSizeTablet'       => '',
	'descFontSizeMobile'       => '',
	'descLineHeight'           => '',
	'descLineHeightType'       => '',
	'descLineHeightTablet'     => '',
	'descLineHeightMobile'     => '',
	'titleLoadGoogleFonts'     => '',
	'descLoadGoogleFonts'      => '',
	'contentPaddingUnit'       => 'px',
	'mobileContentPaddingUnit' => 'px',
	'tabletContentPaddingUnit' => 'px',
	'contentPaddingLink'       => false,
	'titleHrPadding'           => 15,
	'titleVrPadding'           => 15,
	'contentHrPadding'         => 15,
	'contentVrPadding'         => 15,
	'contentTopPadding'        => '',
	'contentBottomPadding'     => '',
	'contentLeftPadding'       => '',
	'contentRightPadding'      => '',
	'titlePaddingUnit'         => 'px',
	'mobileTitlePaddingUnit'   => 'px',
	'tabletTitlePaddingUnit'   => 'px',
	'titlePaddingLink'         => false,
	'layout'                   => 'modern',
	'highlightWidth'           => 10,
	'highlightWidthTablet'     => 10,
	'highlightWidthMobile'     => 10,
	'titleTransform'           => '',
	'titleDecoration'          => '',
	'descTransform'            => '',
	'descDecoration'           => '',
	'titleFontStyle'           => '',
	'descFontStyle'            => '',
	// letter spacing.
	'titleLetterSpacing'       => '',
	'titleLetterSpacingTablet' => '',
	'titleLetterSpacingMobile' => '',
	'titleLetterSpacingType'   => 'px',
	'descLetterSpacing'        => '',
	'descLetterSpacingTablet'  => '',
	'descLetterSpacingMobile'  => '',
	'descLetterSpacingType'    => 'px',
	'titleLeftPadding'         => '',
	'titleRightPadding'        => '',
	'titleTopPadding'          => '',
	'titleBottomPadding'       => '',


);
