<?php
/**
 * Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */

$border_attribute = UAGB_Block_Helper::uag_generate_border_attribute( 'columns' );

return array_merge(
	array(
		'classMigrate'           => false,
		'block_id'               => '',
		'columns'                => '2',
		'align'                  => '',
		'vAlign'                 => '',
		'stack'                  => 'mobile',
		'topPadding'             => '20',
		'bottomPadding'          => '20',
		'leftPadding'            => '20',
		'rightPadding'           => '20',
		'topMargin'              => '0',
		'bottomMargin'           => '0',
		'topPaddingTablet'       => '',
		'bottomPaddingTablet'    => '',
		'leftPaddingTablet'      => '',
		'rightPaddingTablet'     => '',
		'topPaddingMobile'       => '',
		'bottomPaddingMobile'    => '',
		'leftPaddingMobile'      => '',
		'rightPaddingMobile'     => '',
		'topMarginMobile'        => '',
		'bottomMarginMobile'     => '',
		'topMarginTablet'        => '',
		'bottomMarginTablet'     => '',
		'contentWidth'           => 'theme',
		'width'                  => '900',
		'widthType'              => 'px',
		'tag'                    => 'section',
		'backgroundType'         => 'none',
		'backgroundImage'        => '',
		'backgroundPosition'     => 'center-center',
		'backgroundSize'         => 'cover',
		'backgroundRepeat'       => 'no-repeat',
		'backgroundAttachment'   => 'scroll',
		'backgroundVideo'        => '',
		'backgroundColor'        => '',
		'gradientColor1'         => '',
		'gradientColor2'         => '',
		'gradientType'           => 'linear',
		'gradientLocation1'      => '0',
		'gradientLocation2'      => '100',
		'gradientAngle'          => '0',
		'gradientPosition'       => 'center center',
		'selectGradient'         => 'basic',
		'backgroundVideoOpacity' => '50',
		'backgroundVideoColor'   => '',
		'backgroundImageColor'   => '',
		'columnGap'              => '10',
		'bottomType'             => 'none',
		'bottomColor'            => '#333',
		'bottomHeight'           => '',
		'bottomHeightTablet'     => '',
		'bottomHeightMobile'     => '',
		'bottomWidth'            => '',
		'topType'                => 'none',
		'topColor'               => '#333',
		'topHeight'              => '',
		'topHeightTablet'        => '',
		'topHeightMobile'        => '',
		'topWidth'               => '',
		'bottomFlip'             => '',
		'topFlip'                => '',
		'mobileMarginType'       => 'px',
		'tabletMarginType'       => 'px',
		'desktopMarginType'      => 'px',
		'mobilePaddingType'      => 'px',
		'tabletPaddingType'      => 'px',
		'desktopPaddingType'     => 'px',
		'boxShadowColor'         => '',
		'boxShadowHOffset'       => 0,
		'boxShadowVOffset'       => 0,
		'boxShadowBlur'          => '',
		'boxShadowSpread'        => '',
		'boxShadowPosition'      => 'outset',
		'gradientValue'          => 'linear-gradient(90deg, rgb(6, 147, 227, 0.5) 0%, rgb(155, 81, 224, 0.5) 100%)',
		'overlayType'            => 'color',
	),
	$border_attribute
);
