CREATE TABLE SinhVien (
    MSSV VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(255)
);

CREATE TABLE MonHoc (
    MaMH VARCHAR(10) PRIMARY KEY,
    TenMH VARCHAR(255)
);

CREATE TABLE DangKy (
    MSSV VARCHAR(10),
    MaMH VARCHAR(10),
    Ky VARCHAR(10),
    FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH),
    PRIMARY KEY (MSSV, MaMH, Ky)
);
